# Generated by Django 5.2 on 2025-04-21 15:04

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_num', models.CharField(blank=True, max_length=20)),
                ('shaba_num', models.CharField(blank=True, max_length=26)),
                ('cart_num', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('date_of_start', models.DateField()),
                ('installment_amount', models.IntegerField()),
                ('installment_num', models.SmallIntegerField()),
                ('payment_num', models.SmallIntegerField()),
                ('type', models.IntegerField(choices=[(1, 'معمولی'), (2, 'اضطراری'), (3, 'پس انداز')])),
                ('is_active', models.BooleanField(default=True)),
                ('guaranteeing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='guaranteeing', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend', models.IntegerField()),
                ('receipt', models.ImageField(upload_to='receipts/')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('verify', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
