# Generated by Django 5.2 on 2025-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='type',
            field=models.CharField(choices=[('normal', 'معمولی'), ('urgent', 'اضطراری'), ('saving', 'پس انداز')], default='normal', max_length=10),
        ),
    ]
